modLoader="javafml"
loaderVersion="[47,)"
license="AGPLv3"

[[mods]]
modId="accelerated_navigation_terrain_fixture"
version="0.1.0"
displayName="Accelerated Navigation Terrain Fixture"
authors="Scarasol"
description='''Test-only terrain qualification fixture.'''

[[dependencies.accelerated_navigation_terrain_fixture]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.accelerated_navigation_terrain_fixture]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
